<?php
/**
 * Pattern: Features Grid
 *
 * @package Magical_Blocks
 * @since   1.0.0
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'         => __( 'Features Grid', 'magical-blocks' ),
	'description'   => __( 'A grid layout showcasing features with icons, titles, and descriptions.', 'magical-blocks' ),
	'categories'    => array( 'magical-blocks-patterns', 'featured' ),
	'keywords'      => array( 'features', 'grid', 'icons', 'services' ),
	'viewportWidth' => 1200,
	'content'       => '<!-- wp:magical-blocks/container {"blockId":"container-vgsdhvrm","maxWidth":{"desktop":"1200px"},"flexDirection":{"desktop":"column","tablet":"column","mobile":"column"},"alignItems":{"desktop":"center","tablet":"center","mobile":"center"},"paddingTop":{"desktop":"80px","tablet":"60px","mobile":"40px"},"paddingRight":{"desktop":"40px","tablet":"30px","mobile":"20px"},"paddingBottom":{"desktop":"80px","tablet":"60px","mobile":"40px"},"paddingLeft":{"desktop":"40px","tablet":"30px","mobile":"20px"},"metadata":{"categories":["magical-blocks-patterns"],"patternName":"magical-blocks/features-grid","name":"Features Grid"}} -->
<!-- wp:magical-blocks/heading {"blockId":"heading-shbmcxj5","content":"Our Features","textAlign":"center","fontWeight":"700","textColor":"#1e3a5f"} /-->

<!-- wp:magical-blocks/heading {"blockId":"heading-276k69jd","content":"Everything you need to build stunning websites","headingTag":"p","textAlign":"center","fontWeight":"400","textColor":"#666666"} /-->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-hpn6bipf","flexDirection":{"desktop":"row","tablet":"row","mobile":"column"},"justifyContent":{"desktop":"center","tablet":"center","mobile":"center"},"flexWrap":{"desktop":"wrap","tablet":"wrap","mobile":"wrap"},"gap":{"desktop":"30px","tablet":"25px","mobile":"20px"},"paddingTop":{"desktop":"10px","tablet":"30px","mobile":"20px"},"paddingRight":{"desktop":"10px","tablet":"","mobile":""},"paddingBottom":{"desktop":"10px","tablet":"","mobile":""},"paddingLeft":{"desktop":"10px","tablet":"","mobile":""},"paddingLinked":false} -->
<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-4mhhn45c","width":{"desktop":"30%","tablet":"45%","mobile":"100%"},"backgroundColor":"#f0f9ff","paddingTop":{"desktop":"30px"},"paddingRight":{"desktop":"25px"},"paddingBottom":{"desktop":"30px"},"paddingLeft":{"desktop":"25px"},"borderRadius":{"desktop":{"top":"12px","right":"12px","bottom":"12px","left":"12px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"bbf2b06d-f8e1-4f4d-8624-b07cedf4c1cc-puskvyxg","icon":"zap","title":"Fast Performance","description":"Lightning-fast loading times and optimized code for the best user experience."} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-bbf2b06d-f8e1-4f4d-8624-b07cedf4c1cc-puskvyxg mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#4b1ab3;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">Fast Performance</h3><p class="mgb-icon-box-description">Lightning-fast loading times and optimized code for the best user experience.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-reer1r8l","width":{"desktop":"30%","tablet":"45%","mobile":"100%"},"backgroundColor":"#f0fdf4","paddingTop":{"desktop":"30px"},"paddingRight":{"desktop":"25px"},"paddingBottom":{"desktop":"30px"},"paddingLeft":{"desktop":"25px"},"borderRadius":{"desktop":{"top":"12px","right":"12px","bottom":"12px","left":"12px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"6610f99d-d56c-48a0-94ac-729a14d6fa7f-564kepxc","icon":"map","title":"Secure \u0026amp; Reliable","description":"Built with security in mind, keeping your data safe and your site running smoothly."} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-6610f99d-d56c-48a0-94ac-729a14d6fa7f-564kepxc mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#4b1ab3;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="1 6 1 22 8 18 16 22 23 18 23 2 16 6 8 2 1 6"/><line x1="8" y1="2" x2="8" y2="18"/><line x1="16" y1="6" x2="16" y2="22"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">Secure &amp; Reliable</h3><p class="mgb-icon-box-description">Built with security in mind, keeping your data safe and your site running smoothly.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-ygr2uzn6","width":{"desktop":"30%","tablet":"45%","mobile":"100%"},"backgroundColor":"#f0fdf4","paddingTop":{"desktop":"30px"},"paddingRight":{"desktop":"25px"},"paddingBottom":{"desktop":"30px"},"paddingLeft":{"desktop":"25px"},"borderRadius":{"desktop":{"top":"12px","right":"12px","bottom":"12px","left":"12px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"629c6aab-f85f-4cc8-986a-3212d697a478-0y1eshox","icon":"palette","title":"Fully Customizable","description":"Endless customization options to match your brand and design preferences."} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-629c6aab-f85f-4cc8-986a-3212d697a478-0y1eshox mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#4b1ab3;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="13.5" cy="6.5" r=".5"/><circle cx="17.5" cy="10.5" r=".5"/><circle cx="8.5" cy="7.5" r=".5"/><circle cx="6.5" cy="12.5" r=".5"/><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.555C21.965 6.012 17.461 2 12 2z"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">Fully Customizable</h3><p class="mgb-icon-box-description">Endless customization options to match your brand and design preferences.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->
<!-- /wp:magical-blocks/inner-container -->
<!-- /wp:magical-blocks/container -->',
);
