<?php
/**
 * Pattern: Services Section
 *
 * @package Magical_Blocks
 * @since   1.0.0
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'         => __( 'Services Section', 'magical-blocks' ),
	'description'   => __( 'A services section with icon boxes in cards.', 'magical-blocks' ),
	'categories'    => array( 'magical-blocks-patterns' ),
	'keywords'      => array( 'services', 'cards', 'icon box' ),
	'viewportWidth' => 1200,
	'content'       => '<!-- wp:magical-blocks/container {"blockId":"container-8cxwcd1k","maxWidth":{"desktop":"1200px"},"flexDirection":{"desktop":"column","tablet":"column","mobile":"column"},"alignItems":{"desktop":"center","tablet":"center","mobile":"center"},"paddingTop":{"desktop":"80px","tablet":"60px","mobile":"40px"},"paddingRight":{"desktop":"40px","tablet":"30px","mobile":"20px"},"paddingBottom":{"desktop":"80px","tablet":"60px","mobile":"40px"},"paddingLeft":{"desktop":"40px","tablet":"30px","mobile":"20px"},"metadata":{"categories":["magical-blocks-patterns"],"patternName":"magical-blocks/services-section","name":"Services Section"}} -->
<!-- wp:magical-blocks/heading {"blockId":"heading-b08jjqt1","content":"Our Services","textAlign":"center","fontWeight":"700","textColor":"#1e293b"} /-->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-bwv84ml2","flexDirection":{"desktop":"row","tablet":"column","mobile":"column"},"justifyContent":{"desktop":"center","tablet":"center","mobile":"center"},"gap":{"desktop":"30px","tablet":"25px","mobile":"20px"},"paddingTop":{"desktop":"40px","tablet":"30px","mobile":"20px"}} -->
<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-0zd7ur0l","width":{"desktop":"33%","tablet":"100%","mobile":"100%"},"backgroundColor":"#ffffff","paddingTop":{"desktop":"40px"},"paddingRight":{"desktop":"30px"},"paddingBottom":{"desktop":"40px"},"paddingLeft":{"desktop":"30px"},"borderRadius":{"desktop":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"4ae735a8-0944-4f13-9010-d3a301ebe30a-ve8rrtn3","icon":"monitor","title":"Web Development","description":"Custom websites built with the latest technologies and best practices.","iconColor":"#3b82f6"} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-4ae735a8-0944-4f13-9010-d3a301ebe30a-ve8rrtn3 mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#3b82f6;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">Web Development</h3><p class="mgb-icon-box-description">Custom websites built with the latest technologies and best practices.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-6wr9b6c5","width":{"desktop":"33%","tablet":"100%","mobile":"100%"},"backgroundColor":"#ffffff","paddingTop":{"desktop":"40px"},"paddingRight":{"desktop":"30px"},"paddingBottom":{"desktop":"40px"},"paddingLeft":{"desktop":"30px"},"borderRadius":{"desktop":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"fb9574c8-55d5-431e-a8c4-4ed83eee7739-zcigvi42","icon":"layers","title":"UI/UX Design","description":"Beautiful and intuitive designs that enhance user experience.","iconColor":"#ec4899"} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-fb9574c8-55d5-431e-a8c4-4ed83eee7739-zcigvi42 mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#ec4899;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 2 7 12 12 22 7 12 2"/><polyline points="2 17 12 22 22 17"/><polyline points="2 12 12 17 22 12"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">UI/UX Design</h3><p class="mgb-icon-box-description">Beautiful and intuitive designs that enhance user experience.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->

<!-- wp:magical-blocks/inner-container {"blockId":"inner-container-bi1v3zv3","width":{"desktop":"33%","tablet":"100%","mobile":"100%"},"backgroundColor":"#ffffff","paddingTop":{"desktop":"40px"},"paddingRight":{"desktop":"30px"},"paddingBottom":{"desktop":"40px"},"paddingLeft":{"desktop":"30px"},"borderRadius":{"desktop":{"top":"16px","right":"16px","bottom":"16px","left":"16px"}}} -->
<!-- wp:magical-blocks/icon-box {"blockId":"11dd3e1c-28b6-4086-8ea6-ca6426c18c56-njvi0whl","icon":"grid","title":"Digital Marketing","description":"Strategic marketing solutions to grow your online presence.","iconColor":"#f59e0b"} -->
<div class="wp-block-magical-blocks-icon-box mgb-icon-box mgb-icon-box-11dd3e1c-28b6-4086-8ea6-ca6426c18c56-njvi0whl mgb-icon-position-top mgb-align-center" style="--mgb-icon-box-icon-size:48px;--mgb-icon-box-icon-size-tablet:40px;--mgb-icon-box-icon-size-mobile:36px;--mgb-icon-box-icon-color:#f59e0b;--mgb-icon-box-icon-hover-color:#005bb5;--mgb-icon-box-icon-bg:transparent;--mgb-icon-box-icon-bg-hover:transparent;--mgb-icon-box-icon-radius:50%;--mgb-icon-box-icon-padding:16px 16px 16px 16px;--mgb-icon-box-title-color:#1e1e1e;--mgb-icon-box-title-hover-color:#1e1e1e;--mgb-icon-box-desc-color:#666666;--mgb-icon-box-title-size:20px;--mgb-icon-box-title-size-tablet:18px;--mgb-icon-box-title-size-mobile:16px;--mgb-icon-box-title-weight:600;--mgb-icon-box-title-line-height:1.4;--mgb-icon-box-title-spacing:0px;--mgb-icon-box-title-transform:none;--mgb-icon-box-desc-size:16px;--mgb-icon-box-desc-size-tablet:15px;--mgb-icon-box-desc-size-mobile:14px;--mgb-icon-box-desc-weight:400;--mgb-icon-box-desc-line-height:1.6;--mgb-icon-box-desc-spacing:0px;--mgb-icon-box-desc-transform:none;--mgb-icon-box-bg:transparent;--mgb-icon-box-bg-hover:transparent;--mgb-icon-box-border-color:transparent;--mgb-icon-box-border-hover-color:transparent;--mgb-icon-box-border-width:0px;--mgb-icon-box-border-radius:8px;--mgb-icon-box-shadow:none;--mgb-icon-box-shadow-hover:none;--mgb-icon-box-padding:30px 30px 30px 30px;--mgb-icon-box-padding-tablet:24px 24px 24px 24px;--mgb-icon-box-padding-mobile:20px 20px 20px 20px;--mgb-icon-box-margin:0px 0px 0px 0px;--mgb-icon-box-margin-tablet:0px 0px 0px 0px;--mgb-icon-box-margin-mobile:0px 0px 0px 0px;--mgb-icon-box-title-margin:16px;--mgb-icon-box-title-margin-tablet:14px;--mgb-icon-box-title-margin-mobile:12px;--mgb-icon-box-desc-margin:12px;--mgb-icon-box-desc-margin-tablet:10px;--mgb-icon-box-desc-margin-mobile:8px"><div class="mgb-icon-box-inner"><div class="mgb-icon-box-icon"><span class="mgb-icon-box-icon-svg"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg></span></div><div class="mgb-icon-box-content"><h3 class="mgb-icon-box-title">Digital Marketing</h3><p class="mgb-icon-box-description">Strategic marketing solutions to grow your online presence.</p></div></div></div>
<!-- /wp:magical-blocks/icon-box -->
<!-- /wp:magical-blocks/inner-container -->
<!-- /wp:magical-blocks/inner-container -->
<!-- /wp:magical-blocks/container -->',
);
